version: "3"
services:
    db:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
    web:
        build: .
        ports:
            - "8080:8080"
        depends_on:
            - db
        environment: 
            SERVER_ADDRESS: ":8080"
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
            POSTGRES_HOST: db:5432